language: ruby
bundler_args: --without kitchen_vagrant --without development
rvm:
- 2.1.0
cache:
  bundler: true
before_install:
- echo -n $DO_KEY_CHUNK_{0..30} >> ~/.ssh/id_do.base64
- cat ~/.ssh/id_do.base64 | tr -d ' ' | base64 --decode > ~/.ssh/id_do.pem
- echo `md5sum ~/.ssh/id_do.pem`
- ls -la ~/.ssh
script:
- bundle exec kitchen diagnose --all
- bundle exec kitchen test $KITCHEN_INSTANCE
after_script:
- bundle exec kitchen destroy
env:
  global:
  - secure: QWuqIXJry0FS4GgGjTxd6BQsl5l2Cj+ZGxn7+DcBjNl1/Jy23O7GNbMN31sdqJ4/wAvpwGiCUd8mfXMh74+fhI5GGxjUrvURtdvryoE9/jDoBvPBGlFMHvjq78Cyp5q1yxDnzOF1UbWwWF+XVom+jjE2EzRhwfUNgAeX8yOUK6A=
  - secure: MWvJmdUm3W8QIARhCHzaUmI4MIkmpgmJ75BdZV8NlMtmSx3zjpZkRo+pDXUW8ns6R0pc0X0W4Fmm26f/p32hE3cFR+Z2U+0EJuPaVhanu7JSKiDOHusggEuD1vM+E6kroyXJzYYBFhMzPJjeEbmYbpfIiweTuGQbvHUDTcNyTUw=
  - secure: KqmeMhQVVR8RTMK7PrPuloIdanSNcupeKEXo6XibN+OOCdn8DEoOOFKC3UcN4Lep9dSpoXnWTuVuDVPJMDg+jlRPrJjW/myiKKWxHyNYwocNk02wdLbHebExxQCy9k2ywvUQpmCfxzIaocEE2R5rDhnbfFDH6jxUHhfhh3qqksM=
  - secure: MAXi8aXMOipuA2d7sKUHZL8StFQ8k1tj3nGHOSrR3rrMrSQK3bG9FXEQ90F1YigBsRSJ0wPfesrRGCxyuxYaK/oJlMmPHLhSHw2XhuJKi4f8FLQzQQVbrnSdOQUWXXNgZL+xw5Hn8tv6ulNsUR0bN2RvKlF66scBftlDWxRlEho=
  - secure: d3p5Iy9cGVb1xKTch5d7XrvkpKGMYQtUOxad9ZUJHoTDYHMw1XOEcNYiKossusTtuRPh9Y3Vi+9z1vASFbY+oZUUu2oPzHc5WlUHD/ISUdb5e6VS8VGZH0b9qVDvq422jxhkwz4OOI3N5KtfHbhHwKzyJxUWh2zTj2+fNZ+yK+c=
  - secure: JkSEIniwnvStiTvpY1CrxphI/+xkIAJHDkUmURqgslM37rvy0uVN1WhftU6YEzsAqyeTRvTnTNy8wcQWaPFN8uQ2dMavhc/pTyxrgmdg9j6GTF+haauPjWdW/cMSp+73qHu0nKW/CivL5AMLMxwARbU6Q2YLXxE0MMShcasxhZQ=
  - secure: IsYPkc0oYlm+0MLe5LGG1nrufa1FGgcu51Uxo4CI8d5CelJtwRlLZtzJhY67CqgRHZywVClqR7ziCWpKSu7Yxpd3pi4l7XuWbxWjlW2/dWfPD+jr7ykEMMCpWpvYD7V9KtrERxDDKro6Ls5XJLFRwYqct3kDSclRFZ969dfOwLA=
  - secure: GB7UhKYoaRGaRRw1oS1+FBH+Qpd/iHCNlM26u4HX9iEFwwqTjY5JwH/Lh7X9/zD/rwbw7qkqeo7ZOUHl9xiKYN81TfnBOzcElJhFNc6CsbuLfc300RLo85yM/EXfoaIjkdI7WZjWRiY8uFq/to9jp4BVsb+VT+Fc1xuIr4fuS3k=
  - secure: N7ZZKGo3qHrs5QcGhlXQAtJr54an7PJfVVOZIu0xqEuYCyf0UYk8UlEMykQ+o/mBbl1nEvir1Z3uA4KCKBjVPD4nO3alewRrMXVvVnYMZevonne/8oc6gH20YmD+wCsOohEeBXWwjwxLEz8e1l8Afw+ds1kjpls86LJ6sHmS2is=
  - secure: Sjc8NESc7vgfHI3IebPVNpKERgqwpgHjiCtG7Xr40GwvMP0UA0DItWIA/a0OTd4bBfcy73AV+guMhtxmrXLdqq+1/6w2HK48GX8raHOK0PUGsIDmoyhg0S94R3mEuk5j4nbGvYRM4MTgN4H6dvBUh62k+o2pWMyF8EbNzzj25k0=
  - secure: CtKuyn4tyBZznZAVaR7SmPb3CPZqJ+gyl2PrfzVobDQq/TdgElGlfCIamQwuKTBE0KWjhtbKlPkwOCEZOBQG8VZFvjqNZ2RT8o/hDuFTWLy/jn7f9H/PgRtOw4eWQHWHqpKrg17Itl1x/RBcOyIBl8h1wTIvox6boDNtNhiMjgE=
  matrix:
  - KITCHEN_INSTANCE='default-centos-65'
